site_name: Documentação Projeto Scraping
theme:
  name: material
  palette:
    primary: blue
  language: pt

repo_name: "Vitor-HM/ScrapingProjeto"
repo_url: "https://github.com/Vitor-HM/ScrapingProjeto"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - search
  - mkdocstrings:
      default_handler: python
